# Generated by Django 5.2.7 on 2025-11-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=128)),
                ('pattern', models.CharField(blank=True, max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('supplier_id', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
