# Generated by Django 5.2.8 on 2025-11-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
